# Generated by Django 6.1.1 on 2026-09-19 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_notification_comment_notification_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='thứ tự')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='accounts.company')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='thứ tự')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='accounts.company')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Đang xử lý'), ('served', 'Đã phục vụ'), ('cancelled', 'Đã hủy')], default='pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('goods', 'Hàng hóa'), ('food', 'Món ăn'), ('drink', 'Nước uống')], default='goods', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='cái', max_length=50, verbose_name='đơn vị tính')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='mã sản phẩm')),
                ('image', models.FileField(blank=True, null=True, upload_to='products/%Y/%m/')),
                ('track_stock', models.BooleanField(default=False, help_text='Chỉ áp dụng cho hàng hóa, không dùng cho món ăn/nước uống.', verbose_name='quản lý tồn kho')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='tồn kho')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('table_type', models.CharField(choices=[('dining', 'Bàn ăn'), ('billiards', 'Bàn bi-a'), ('karaoke', 'Phòng karaoke'), ('other', 'Khác')], default='dining', max_length=10)),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='sức chứa')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Áp dụng cho bàn bi-a / phòng karaoke. Để trống nếu không tính tiền theo giờ.', max_digits=12, null=True, verbose_name='giá thuê theo giờ')),
                ('pos_x', models.FloatField(default=0, verbose_name='vị trí X')),
                ('pos_y', models.FloatField(default=0, verbose_name='vị trí Y')),
                ('width', models.FloatField(default=1)),
                ('height', models.FloatField(default=1)),
                ('status', models.CharField(choices=[('available', 'Trống'), ('occupied', 'Đang sử dụng'), ('reserved', 'Đã đặt trước'), ('cleaning', 'Đang dọn dẹp')], default='available', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='accounts.company')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='store.floor')),
            ],
            options={
                'ordering': ['floor__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_count', models.PositiveIntegerField(default=1, verbose_name='số khách')),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('closed', 'Đã đóng')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('rental_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tính từ hourly_rate khi đóng phiên, 0 nếu bàn không tính giờ.', max_digits=12, verbose_name='tiền thuê bàn')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='store.table')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Để trống nếu là đơn mang về / không gắn bàn.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.tablesession'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_category_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_floor_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('company', 'sku'), name='unique_product_sku_per_company'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('floor', 'name'), name='unique_table_name_per_floor'),
        ),
        migrations.AddConstraint(
            model_name='tablesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('table',), name='unique_open_session_per_table'),
        ),
    ]
