# Generated by Django 6.1.1 on 2026-09-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, help_text='Đánh dấu thủ công (vd. món hết nguyên liệu hôm nay) — với hàng có quản lý tồn kho thì tồn kho về 0 cũng tự tính là hết hàng.', verbose_name='hết hàng'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='hiển thị cho khách order'),
        ),
    ]
