# Generated by Django 6.1.1 on 2026-09-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_department_user_department_position_user_position_and_more'),
        ('store', '0003_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='card_minutes_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='số phút trừ từ thẻ hội viên'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Hội viên đang ngồi bàn này, nếu có — dùng để trừ giờ thẻ hội viên khi đóng phiên.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_sessions', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='rental_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tính từ hourly_rate khi đóng phiên, sau khi trừ phần đã trả bằng giờ thẻ hội viên (nếu có).', max_digits=12, verbose_name='tiền thuê bàn'),
        ),
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Đã nhận bàn')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_bookings', to='accounts.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='store.customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='store.table')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['company', 'table', 'start_time'], name='store_table_company_702fc7_idx')],
            },
        ),
    ]
