# Generated by Django 6.1.1 on 2026-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_tablesession_card_minutes_used_tablesession_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='camera_url',
            field=models.URLField(blank=True, help_text='Link stream (HLS .m3u8) hoặc trang embed của camera gắn tại bàn này — dùng cho nút "Check VAR" trên app hội viên. Để trống nếu bàn chưa lắp camera.', max_length=500, verbose_name='link camera bàn'),
        ),
    ]
