# Generated by Django 6.1.1 on 2026-09-23 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_department_user_department_position_user_position_and_more'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/', verbose_name='ảnh')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='hiển thị')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.company')),
            ],
            options={
                'ordering': ['order', '-start_time', '-pk'],
            },
        ),
    ]
