# Generated by Django 6.1.1 on 2026-09-23 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_department_user_department_position_user_position_and_more'),
        ('membership', '0002_event'),
        ('store', '0004_tablesession_card_minutes_used_tablesession_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_accounts', to='accounts.company')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_account', to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PointsRedemptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('points_cost', models.PositiveIntegerField()),
                ('minutes_reward', models.PositiveIntegerField(verbose_name='phút được cộng')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='thứ tự')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_redemption_options', to='accounts.company')),
            ],
            options={
                'ordering': ['order', 'points_cost'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earn_spend', 'Tích lũy từ chi tiêu'), ('earn_visit', 'Thưởng lượt ghé quán'), ('earn_manual', 'Nhân viên cộng tay'), ('redeem', 'Đổi điểm'), ('adjust', 'Điều chỉnh')], max_length=12)),
                ('points', models.IntegerField(help_text='Dương = cộng, âm = trừ.')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='membership.pointsaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='store.tablesession')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('fixed', 'Giảm số tiền cố định'), ('percent', 'Giảm theo phần trăm')], default='fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Số tiền (đ) nếu giảm cố định, hoặc số % (0-100) nếu giảm theo phần trăm.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Còn hiệu lực'), ('used', 'Đã dùng'), ('expired', 'Hết hạn')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_vouchers', to='accounts.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='store.customer')),
                ('used_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.tablesession')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='membership.voucher')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
