# Generated by Django 6.1.1 on 2026-09-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommember',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Lần cuối user xem tin nhắn của room này.', null=True),
        ),
    ]
