# Generated by Django 6.1.1 on 2026-09-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroommember_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommember',
            name='is_muted',
            field=models.BooleanField(default=False, verbose_name='tắt thông báo'),
        ),
    ]
