# Generated by Django 6.1.1 on 2026-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroommember_is_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommember',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='ghim'),
        ),
    ]
