# Generated by Django 6.1.1 on 2026-09-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroommember_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='attachments_enabled',
            field=models.BooleanField(default=True, help_text='Tắt: chỉ chủ/phó phòng được gửi file/link.', verbose_name='cho phép gửi đính kèm'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_enabled',
            field=models.BooleanField(default=True, help_text='Tắt: chỉ chủ/phó phòng được nhắn tin (chế độ chỉ thông báo).', verbose_name='cho phép chat'),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='role',
            field=models.CharField(choices=[('owner', 'Chủ phòng'), ('deputy', 'Phó phòng'), ('member', 'Thành viên')], default='member', max_length=10),
        ),
    ]
