# Generated by Django 6.1.1 on 2026-09-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_attachments_enabled_chatroom_chat_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='preview_data_url',
            field=models.TextField(blank=True),
        ),
    ]
