# Generated by Django 6.1.1 on 2026-09-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_attachment_preview_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_room_avatars/%Y/%m/'),
        ),
    ]
