# Generated by Django 6.1.1 on 2026-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_plan_company_address_company_business_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='tên hiển thị'),
        ),
    ]
