# Generated by Django 6.1.1 on 2026-09-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='True nếu user chưa từng tự đổi mật khẩu ban đầu (do admin cấp).', verbose_name='phải đổi mật khẩu'),
        ),
    ]
