# Generated by Django 6.1.1 on 2026-09-19 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='cấu hình')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='accounts.company')),
            ],
        ),
    ]
