# Generated by Django 6.1.1 on 2026-09-19 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_public',
            field=models.BooleanField(default=True, help_text='True: gửi cho cả công ty. False: chỉ gửi riêng cho user ở field target.', verbose_name='công khai toàn công ty'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(blank=True, help_text='User nhận riêng, chỉ có ý nghĩa khi is_public=False.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_public', True), ('target__isnull', True)), models.Q(('is_public', False), ('target__isnull', False)), _connector='OR'), name='notification_target_matches_is_public'),
        ),
    ]
