# Generated by Django 6.1.1 on 2026-09-21 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_notification_comment_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_preview_data_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='tên hiển thị'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='link facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Ảnh đại diện ngoài (vd: từ mạng xã hội), dùng khi chưa upload avatar.'),
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=150, verbose_name='tên ngân hàng')),
                ('bin_code', models.CharField(max_length=10, verbose_name='mã BIN ngân hàng')),
                ('account_holder', models.CharField(max_length=150, verbose_name='chủ tài khoản')),
                ('account_number', models.CharField(max_length=50, verbose_name='số tài khoản')),
                ('is_primary', models.BooleanField(default=False, verbose_name='thẻ chính')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('user', 'bin_code', 'account_number'), name='unique_bank_card_per_user')],
            },
        ),
    ]
