# Generated by Django 6.1.1 on 2026-09-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_avatar_profile_avatar_preview_data_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/%Y/%m/', verbose_name='ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='ghi chú cá nhân'),
        ),
    ]
