# Generated by Django 6.1.1 on 2026-09-21 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_cover_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='tên phòng ban')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.company')),
                ('head', models.ForeignKey(blank=True, help_text='Trưởng phòng.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Phòng ban cấp trên, để trống nếu là phòng ban gốc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Phòng ban của user. Phải thuộc cùng company với user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.department'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='chức vụ')),
                ('level', models.PositiveIntegerField(default=0, help_text='Số càng nhỏ càng cao trong sơ đồ tổ chức (0 = cao nhất).', verbose_name='cấp bậc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.company')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Chức vụ của user. Phải thuộc cùng company với user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='accounts.position'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'parent'], name='accounts_de_company_566baa_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_department_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_position_name_per_company'),
        ),
    ]
