# Generated by Django 6.1.1 on 2026-09-19 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_notification_comment_notification_title'),
        ('store', '0002_product_is_out_of_stock_product_show_in_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='thứ tự')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_categories', to='accounts.company')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='kg', max_length=50, verbose_name='đơn vị tính')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='mã kho')),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='tồn kho hiện tại')),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=3, help_text='Cảnh báo khi tồn kho xuống dưới mức này. Để trống nếu không cần cảnh báo.', max_digits=14, null=True, verbose_name='ngưỡng cảnh báo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='inventory.stockcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='định lượng / 1 sản phẩm')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.productrecipe')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Nhập kho'), ('out', 'Xuất kho')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='đơn giá')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='ghi chú / tham chiếu')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurred_date', models.DateField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_stockcategory_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['company', 'category'], name='stockitem_company_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('company', 'sku'), name='unique_stockitem_sku_per_company'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(fields=('recipe', 'stock_item'), name='unique_recipe_item'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'occurred_date'], name='stockmove_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'occurred_date'], name='stockmove_item_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'movement_type', 'occurred_date'], name='stockmove_type_date_idx'),
        ),
    ]
