from django.urls import path

from .api import (
    BookingCancelView,
    BookingListCreateView,
    CardTransactionListView,
    CustomerLoginView,
    CustomerVoucherListView,
    CustomerVoucherUseView,
    EventListView,
    FloorListView,
    MenuView,
    MeView,
    MySessionView,
    PaymentQrView,
    PlanListView,
    PointsRedemptionOptionListView,
    PointsRedeemView,
    PointsTransactionListView,
    PointsView,
    RequestPaymentView,
    RequestTableUseView,
    SwitchTableView,
    TableDetailView,
    TableListView,
)

app_name = 'membership'
urlpatterns = [
    path('auth/login/', CustomerLoginView.as_view(), name='login'),
    path('me/', MeView.as_view(), name='me'),
    path('plans/', PlanListView.as_view(), name='plans'),
    path('card/transactions/', CardTransactionListView.as_view(), name='card-transactions'),
    path('menu/', MenuView.as_view(), name='menu'),
    path('events/', EventListView.as_view(), name='events'),
    path('floors/', FloorListView.as_view(), name='floors'),
    path('tables/', TableListView.as_view(), name='tables'),
    path('tables/<int:pk>/', TableDetailView.as_view(), name='table-detail'),
    path('tables/<int:table_id>/request-use/', RequestTableUseView.as_view(), name='table-request-use'),
    path('my-session/', MySessionView.as_view(), name='my-session'),
    path('sessions/<int:session_id>/request-payment/', RequestPaymentView.as_view(), name='request-payment'),
    path('sessions/<int:session_id>/payment-qr/', PaymentQrView.as_view(), name='payment-qr'),
    path('sessions/<int:session_id>/switch-table/', SwitchTableView.as_view(), name='switch-table'),
    path('bookings/', BookingListCreateView.as_view(), name='bookings'),
    path('bookings/<int:pk>/cancel/', BookingCancelView.as_view(), name='booking-cancel'),
    path('points/', PointsView.as_view(), name='points'),
    path('points/transactions/', PointsTransactionListView.as_view(), name='points-transactions'),
    path('points/redemption-options/', PointsRedemptionOptionListView.as_view(), name='points-redemption-options'),
    path('points/redeem/', PointsRedeemView.as_view(), name='points-redeem'),
    path('vouchers/', CustomerVoucherListView.as_view(), name='vouchers'),
    path('vouchers/<int:pk>/use/', CustomerVoucherUseView.as_view(), name='voucher-use'),
]
